sonar.projectKey=plageoj_jot-deck
sonar.organization=plageoj

sonar.sources=packages/app/src,crates/core/src
sonar.tests=packages/app/src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.rust.lcov.reportPaths=coverage/rust/lcov.info
